pub mod discussion;
pub mod harness_exec;
pub mod cda;
pub mod chapter;
pub mod character;
pub mod consistency;
pub mod harness;
pub mod http;
pub mod inspiration;
pub mod llm;
pub(crate) mod llm_helper;
pub mod memory;
pub mod model;
pub mod plugin;
/// IPC 命令模块
pub mod project;
pub mod settings;
pub mod style;
pub mod world;
